version: "3.9"
services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"

  ui:
    build: .
    command: streamlit run ui/streamlit_app.py --server.address 0.0.0.0 --server.port 8501
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
    ports:
      - "8501:8501"
    depends_on:
      - api

  orthanc:
    image: jodogne/orthanc-plugins:latest
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - ./data/orthanc:/var/lib/orthanc/db
